name: CI

on:
  push:
  pull_request:

jobs:
  image:
    name: Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fallenbreath
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mcdreforged/website
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Store Git Info
        run: |
          cat > git-info.json <<EOF
          {
            "branch": "$(git rev-parse --abbrev-ref HEAD)",
            "commitHash": "$(git rev-parse HEAD)"
          }
          EOF

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Website deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev')
    needs:
      - image
    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          fingerprint: ${{ secrets.DEPLOY_SSH_FINGERPRINT }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: ${{ secrets.DEPLOY_SSH_SCRIPT }} ${{ github.ref }}
